name: invoice_tracking_flutter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  another_flushbar: ^1.12.29
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: null
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  form_builder_validators: ^8.4.0
  freezed_annotation: ^2.2.0
  go_router: ^6.0.0
  im_stepper: ^1.0.1+1
  image_picker: ^0.8.6
  intl: ^0.17.0
  introduction_screen: ^3.1.1
  json_theme: ^4.0.1+3
  path: null
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  persistent_bottom_nav_bar_v2: ^4.2.6
  shared_preferences: ^2.0.15
  sizer: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"

  web: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/
    - assets/themes/
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
